[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nombre_de_tu_api"
version = "0.1.0"
license = "LGPL-3.0-or-later"  # Ajusta según tu licencia real
description = "Descripción de tu API"
EOF