""" Agregar Enum a las columnas Category

Revision ID: 2b598c7ad377
Revises: c35f15585885
Create Date: 2025-03-21 15:04:14.107376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b598c7ad377'
down_revision: Union[str, None] = 'c35f15585885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Crea Enum para category
    category_enum = sa.Enum('WORK', 'STUDY', 'UNKNOWN', name='category')
    category_enum.create(op.get_bind())

    op.alter_column('tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # Remueve el valor por defecto
    op.execute("ALTER TABLE tasks ALTER COLUMN category DROP DEFAULT")
    
    # Actualiza valores por defecto a Enum category
    op.execute("UPDATE tasks SET category = 'UNKNOWN'")

    # Alter the column to use the new Enum type with USING clause
    op.execute("ALTER TABLE tasks ALTER COLUMN category TYPE category USING category::category")
    
    # Set the default value again
    op.execute("ALTER TABLE tasks ALTER COLUMN category SET DEFAULT 'UNKNOWN'::category")
    


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'category',
               existing_type=sa.Enum('WORK', 'STUDY', 'UNKNOWN', name='category'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
