"""Corrige nombres de relación Tags.tasks para back_populates correcto

Revision ID: d7bb395cc787
Revises: bf03127d608d
Create Date: 2025-03-06 17:46:37.526717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7bb395cc787'
down_revision: Union[str, None] = 'bf03127d608d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
