"""empty message

Revision ID: 32bc2e578a19
Revises: a19aa17c9e3e
Create Date: 2025-03-28 09:42:13.857395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32bc2e578a19'
down_revision: Union[str, None] = 'a19aa17c9e3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_notes',
    sa.Column('original_user_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('shared_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['original_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['shared_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('original_user_id', 'note_id', 'shared_user_id')
    )
    op.create_index(op.f('ix_sessions_is_active'), 'sessions', ['is_active'], unique=False)
    op.drop_constraint('sessions_user_id_fkey', 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_user_id_fkey', 'sessions', 'users', ['user_id'], ['user_id'])
    op.drop_index(op.f('ix_sessions_is_active'), table_name='sessions')
    op.drop_table('shared_notes')
    # ### end Alembic commands ###
