"""empty message

Revision ID: 1ac0fdeed628
Revises: 32bc2e578a19
Create Date: 2025-03-30 11:45:52.358941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ac0fdeed628'
down_revision: Union[str, None] = '32bc2e578a19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define el Enum fuera de las funciones upgrade y downgrade
shared_permission_enum = sa.Enum('READ', 'WRITE', name='shared_permission')

def upgrade() -> None:
    # Crea el tipo Enum en la base de datos
    shared_permission_enum.create(op.get_bind())

    # Agrega la columna 'permission' utilizando el objeto Enum
    op.add_column(
        'shared_notes',
        sa.Column(
            'permission',
            shared_permission_enum,  # Usa el objeto Enum definido
            nullable=False,
            server_default='READ'
            # Para PostgreSQL, puedes ser más explícito:
            # server_default=text("'READ'::shared_permission")
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shared_notes', 'permission')
    # ### end Alembic commands ###
