"""empty message

Revision ID: 5a676d3bef10
Revises: a246743ddac9
Create Date: 2025-03-23 10:40:11.481116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a676d3bef10'
down_revision: Union[str, None] = 'a246743ddac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('create_at', sa.DateTime(), nullable=False, server_default="2025-03-23 10:40:58.571445"))
    op.alter_column('notes', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('notes', 'create_date')
    op.drop_column('notes', 'create_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('create_time', postgresql.TIME(), server_default=sa.text("'00:00:00.265359'::time without time zone"), autoincrement=False, nullable=False))
    op.add_column('notes', sa.Column('create_date', sa.DATE(), autoincrement=False, nullable=False))
    op.alter_column('notes', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('notes', 'create_at')
    # ### end Alembic commands ###
